 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Marwan Aboulfath
 ******************************************************************************/

#include "Port.h"
/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif


const Port_ConfigType Port_Configuration = {
                            /* PORT A Configurations */
                            PORT_PORTA, PORT_PIN0, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTA, PORT_PIN1, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTA, PORT_PIN2, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTA, PORT_PIN3, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTA, PORT_PIN4, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTA, PORT_PIN5, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTA, PORT_PIN6, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTA, PORT_PIN7, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            /* PORT B Configurations */
                            PORT_PORTB, PORT_PIN0, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTB, PORT_PIN1, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTB, PORT_PIN2, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTB, PORT_PIN3, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTB, PORT_PIN4, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTB, PORT_PIN5, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTB, PORT_PIN6, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTB, PORT_PIN7, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            /* PORT C Configurations */
                            PORT_PORTC, PORT_PIN0, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTC, PORT_PIN1, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTC, PORT_PIN2, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTC, PORT_PIN3, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTC, PORT_PIN4, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTC, PORT_PIN5, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTC, PORT_PIN6, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTC, PORT_PIN7, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            /* PORT D Configurations */
                            PORT_PORTD, PORT_PIN0, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTD, PORT_PIN1, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTD, PORT_PIN2, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTD, PORT_PIN3, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTD, PORT_PIN4, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTD, PORT_PIN5, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTD, PORT_PIN6, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTD, PORT_PIN7, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            /* PORT E Configurations */
                            PORT_PORTE, PORT_PIN0, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTE, PORT_PIN1, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTE, PORT_PIN2, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTE, PORT_PIN3, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTE, PORT_PIN4, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTE, PORT_PIN5, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            /* PORT F Configurations */
                            PORT_PORTF, PORT_PIN0, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTF, PORT_PIN1, PORT_PIN_OUT, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, FALSE, FALSE,        /* LED pin Set as OUTPUT pin, Initial level LOW, Mode DIO */
                            PORT_PORTF, PORT_PIN2, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTF, PORT_PIN3, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE,
                            PORT_PORTF, PORT_PIN4, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, TRUE, TRUE        /* SWITCH pin Set as INPUT pin, PULL UP resistance ON, Mode DIO */

};


